# Generated by Django 5.2.16 on 2026-07-22 12:54

from django.db import migrations, models

def populate_unique_phone_numbers(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    seen = set()
    for user in User.objects.all():
        phone = (user.phone_number or '').strip()
        if not phone or phone in seen:
            user.phone_number = f"980000{user.id:04d}"
            user.save()
            seen.add(user.phone_number)
        else:
            seen.add(phone)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_unique_phone_numbers, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]


