# Generated by Django 5.2.16 on 2026-07-22 13:19

from django.db import migrations, models

def populate_unique_emails(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    seen = set()
    for user in User.objects.all():
        email = (user.email or '').strip().lower()
        if not email or email in seen:
            user.email = f"user_{user.id}@example.com"
            user.save()
            seen.add(user.email)
        else:
            seen.add(email)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email_alter_user_phone_number'),
    ]

    operations = [
        migrations.RunPython(populate_unique_emails, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]

